---
- name: The first play
  hosts: local_test
  # hosts: all
  # strategy: free
  # hosts: localhost
  # become: yes
  # hosts: local_ssh
  roles:
    # expect to load from ~/.ansible/content
    - GROG.debug-variable.debug-variable
    - ansible_core.source_control.source_control
    # expect to install from playbook relative roles/
    - bad_role_playbook_relative
    # - myrole
    # - role2
    # - some_required_role1
    # - role_with_sub_roles
    # - role_with_deps
    # - ROLEA
    # - ../../../somerole
    # - ROLEB
    # - ROLEC
  tags:
    - the_play_tag
  vars:
    baz: "BAZZZZZZZZZZZZZZZ"
  tasks:
    - block:
        - name: Include a role that will fail
          include_role:
            name: a_role_to_include
            #            tasks_from: fail.yml

      rescue:
        - name: import the role called 'a_role_to_include' without the namespace FAILED
          debug:
            msg: "a_role_to_include failed to import"

            #       always:

    - block:
        - name: import the role called 'alikins.a_role_to_include' with namespace but without repo name
          include_role:
            name: alikins.a_role_to_include
            # register: include_role_result
      rescue:
        - name: import the role called 'alikins.a_role_to_include' with namespace but without repo name FAILED
          debug:
            msg: "import the role called 'alikins.a_role_to_include' with namespace but without repo name FAILED"

    - name: import the role called 'alikins.multiple_roles.a_role_to_include' with namespace and repo name and role name
      include_role:
        name: alikins.multiple_roles.a_role_to_include
      register: include_role_result
      # ignore_errors: True

    - name: show include_role result
      debug:
        var: include_role_result


    - name: blip
      tags:
        - the_task_tag
      debug:
        var: baz

    - name: try to find git_config2 in first play
      git_config2:
        name: alias.ci
        scope: global
      register: git_config_result

    - name: show git_config result
      debug:
        var: git_config_result


- name: the second second play
  hosts: local_test
  roles:
    # from ~/.ansible/content
    - testing.ansible_testing_content.test-role-a
  gather_facts: true
  tasks:
    - name: release
      shell: cat /etc/os-release
      register: release_result

    - debug:
        var: release_result.cmd

    - name: import the role called 'geerlingguy.apache' from ~/.ansible/content
      include_role:
        name: geerlingguy.apache.apache
      register: include_role_apache_result

    - name: show include_role_apache_result
      debug:
        var: include_role_apache_result
